### ISSUE TITLE
plugin does not work on Linux -- you cannot dloopen an svp file because it is not ELF format

### ISSUE THREAD

**Issue by Corin-EU** [TTK-qmmp/qmmp-sonique#1]
if the OS is Linux  on line 291 it states to open the Sonique SVP file with

                m_instance = dlopen(module_path);

but this will never work because a Sonique SVP file is PE32 executable (DLL) and so is not in ELF format which is the only format that dlopen on Linux can handle.

             void SoniqueWidget::generatePreset()
             {

              closePreset();

            const char *module_path = qPrintable(m_presetList[m_currentIndex]);
            fprintf (stderr, "the module path is -->%s<--\n", module_path);
            #ifdef Q_OS_UNIX
             fprintf (stderr, "calling dllpen with specified module_path ...\n");
             m_instance = dlopen(module_path, RTLD_LAZY);
             fprintf (stderr, "did we get a moduleinstance from -->%s<--\n", module_path);
            #else
            fprintf (stderr, "calling LoadLibraryA with specified module_path<--\n");
            m_instance = LoadLibraryA(module_path);
            #endif
            qDebug("[SoniqueWidget] url is %s", module_path);

           if(!m_instance)
          {
           fprintf( stderr, "dlopen get error: %s\n", dlerror() );
           qDebug("Could not load the svp file %s", module_path);
           return;
          }

log output is

        the module path is -->//ust/local/bin/qmmp-1.5.0/bin/sonique/Faited.svp<--
        calling dlopen with specified module_path ...
        did we get a moduleinstance from -->local/bin/qmmp-1.5.0/bin/sonique/Faited.svp<--
        [SoniqueWidget] url is local/bin/sonique/Faited.svp
        dlopen get error: /usr/local/bin/sonique/Faited.svp: invalid ELF header
        Could not load the svp file local/bin/sonique/Faited.svp

Why the sonique SVP file directory has been coded as a sub-directory the application path viz /usr/local/bin/sonique and not to a lib or a share diirectory or to the userś home .qmmp/sonique is anybodyś guess.  It appears that this code was never tested on a Linux system before it was released.

**Comment by Greedysky** [comment]
sorry, this plugin can only run on Windows.

**Comment by Corin-EU** [comment]
Exactly, so please consider adding a line tothe README file -- WINDOWS ONLY -- as that would make it clear even thought the code "#ifdef Q_OS_UNIX" makes it appear that it will work on other platforms.
